name: nlp-classifier

channels:
  - default

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - ipykernel
  - pytest
  - pip
  - pip:
    - nltk
    - python-dotenv
    - black
    - ruff
    - pre-commit
